# Generated by Django 4.1.7 on 2023-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_address', models.CharField(max_length=50)),
                ('sub_city', models.CharField(max_length=50)),
                ('sub_state', models.CharField(max_length=2)),
                ('sub_zip', models.IntegerField(default=95747)),
                ('sub_date_added', models.DateTimeField(verbose_name='sub added')),
            ],
        ),
    ]
