# Generated by Django 4.1.7 on 2023-04-03 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_architects_architectscontacts_owners_ownerscontacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.architects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.owners'),
        ),
    ]
