# Generated by Django 4.1.7 on 2023-04-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='plans',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_bid', to='projects.projects'),
        ),
    ]
