# Generated by Django 4.1.7 on 2023-04-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='sub_bids_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
