# Generated by Django 4.1.7 on 2023-04-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_bids_sub_bids_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architects',
            options={'verbose_name': 'Architect', 'verbose_name_plural': 'Architects'},
        ),
        migrations.AlterModelOptions(
            name='architectscontacts',
            options={'verbose_name': 'Architect Contact', 'verbose_name_plural': 'Architect Contacts'},
        ),
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelOptions(
            name='ownerscontacts',
            options={'verbose_name': 'Owner Contact', 'verbose_name_plural': 'Owner Contacts'},
        ),
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='projectnotes',
            options={'verbose_name': 'Project Note', 'verbose_name_plural': 'Project Notes'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
