# Generated by Django 4.1.7 on 2023-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=200)),
                ('task_complete', models.IntegerField(default=0)),
                ('task_created', models.DateTimeField(verbose_name='task created')),
            ],
        ),
    ]
