# Generated by Django 4.1.7 on 2023-03-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_created',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_complete',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_description',
        ),
        migrations.AddField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='new title', max_length=40),
            preserve_default=False,
        ),
    ]
