# Generated by Django 4.1.7 on 2023-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('assigned_to', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
