# Generated by Django 4.1.7 on 2023-03-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_alter_subnotes_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractors',
            name='primary_contact',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
